config/routes.rb
Project2::Application.routes.draw do
  get 'comments/index'

  get 'sites/index'

  root to: 'sites#index'
  resources :sites do
    resources :comments
  end

end

app/models/comment.rb
class Comment <ActiveRecord::Base
  belongs_to :site

  validates :user, presence: true
end

app/models/site.rb
class Site <ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :location, presence:  true
  validates :construction_type, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "hi", password: "k", only:
  # :destroy

  def create
    @site = Site.find(params[:site_id])
    @comment = @site.comments.create!(comment_params)
    redirect_to sites_path
  end

  def destroy
    @site = Site.find(params[:site_id])
    @comment = @site.comments.find(params[:id])
    @comment.destroy
    redirect_to sites_path(@site)
  end

  private
  def comment_params
    params.require(:comment).permit(:user, :link, :text)
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # http_basic_authenticate_with name: "hi", password: "k", except:
  # [:index, :show]


  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = Site.new
  end

  def edit
    @site = Site.find(params[:id])
  end

  def create
    @site = Site.create!(site_params)

    if @site.save
      redirect_to @site
    else
      render 'new'
    end
  end

  def update
    @site = Site.find(params[:id])

    if @site.update(site_params)
      redirect_to sites_path
    else
      render 'edit'
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path
  end

  private
  def site_params
    params.require(:site).permit(:location, :construction_type, :building_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/comments/_comment.html.erb
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->

  <p>
    <%= comment.user%>
    says:
  </p>

  <p>
    <%= comment.text %>
  </p>

  <p>
    More information can be found here: <%= comment.link %>
  </p>

  <p>
    Comment added: <%= time_ago_in_words(comment.updated_at) %> ago
  </p>

  <p>
  <%= link_to "Remove Comment", [comment.site, comment],
          method: :delete,
          data: {confirm: "Are you sure you would like to delete this comment?"} %>
  </p>
  <br>

app/views/comments/_form.html.erb
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->

<%= form_for ([@site, @site.comments.build]) do |f| %>
  <p>
    <%= f.label :user %>
    <%= f.text_field :user %>
  </p>

<p>
    <%= f.label :link %>
    <%= f.text_field :link %>
</p>

  <p>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->

</head>


<!-- <div class="hero-unit"> -->
<div class="container">
    <nav>
    <h1>DC Development Map</h1>
    <h3> <%= link_to "View All Locations", sites_path %> | <%= link_to "Add Location", new_site_path %> </h3>
  </nav>
<body>

  <%= yield %>

</body>
</div>
</html>

app/views/sites/_form.html.erb
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"> -->

<%= form_for @site do |f| %>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location%>
  </p>

<!-- <div class="input-field col s12"> -->
  <p>
    Construction Type
    <!-- <%= f.text_field :construction_type %> -->
    <%= f.select :construction_type, ["New", "Rennovation"] %>
  </p>
<!-- </div> -->

  <p>
     Building Type (mixed use, commercial, etc.)
    <%= f.text_area :building_type %>
  </p>

  <!-- <p>
    Site Location:
      <%= f.text_field :location%>
  </p> -->

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/sites/edit.html.erb
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"> -->

<h2> Enter Edits for <%= @site.location %> </h2>

<%= render 'form' %>

app/views/sites/index.html.erb
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"> -->


<h2>Development Locations</h2>

<% @sites.each do |list| %>
  <h3><%= link_to list.location, list %></h3>
  <%= link_to "Delete", site_path(list),
        method: :delete,
        data: {confirm: "Are you sure you would like to delete?"} %>
         |
  <%= link_to "Edit", edit_site_path(list) %>
<ul>
  <li>Type of construction: <%= list.construction_type %></li>
  <li>Building type: <%= list.building_type %></li>
  <li>Last updated <%= time_ago_in_words(list.updated_at) %> ago </li>
</ul>
<% end %>

app/views/sites/new.html.erb
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"> -->

<h2> Adding a New Location </h2>
<h2> Does the site already exist? Please check <%= link_to "here", sites_path %> prior to entering a new location. </h2>


<%= render 'form' %>

app/views/sites/show.html.erb
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"> -->

<h2> Viewing <%= @site.location %> </h2>

<p>
  Type of construction:
  <%= @site.construction_type %>
</p>
<p>
  Building type:
  <%= @site.building_type %>
</p>
<p>
  Site:
</p>
<br>

  <iframe width="350" height="250" frameborder="10" src="//www.google.com/maps/embed/v1/place?q=Macys,New%20York,%20New%20York,%20USA
      &zoom=17
      &key=AIzaSyDBqG3hEoUoYKbZPgY75AxrzadBGiiO4qU">
  </iframe>


<h2>Comments</h2>
<%= render @site.comments %>

<h2> Add a commment: </h2>

<%= render 'comments/form' %>